services:
  redis:
    profiles: ["backend", "services"]
    image: redis:6.2.3
    networks:
      - whip_nw
    ports:
      - 6379:6379
  api:
    profiles: ["backend"]
    image: butter_whip/backend:dev
    build:
      context: ./backend
      args:
        TAG: python3.9
    ports:
      - 80:80
    networks:
      - whip_nw
    depends_on:
      - redis
      - sched
    env_file:
      - backend/.env
    volumes:
      - ./backend/app/:/app/app/
      - ./backend/main.py:/app/main.py
    command: "uvicorn --reload --host 0.0.0.0 --port 80 --log-level info app.endpoints:app"
  sched:
    profiles: ["backend", "services"]
    image: butter_whip/backend:dev
    build:
      context: ./backend
      args:
        TAG: python3.9
    networks:
      - whip_nw
    depends_on:
      - redis
    env_file:
      - backend/.env
    volumes:
      - ./backend/app/:/app/app/
      - ./backend/main.py:/app/main.py
    command: "celery -A app.celery_main worker --concurrency=2 -B -l INFO --pidfile="
  frontend:
    profiles: ["frontend"]
    image: butter_whip/frontend:dev
    build: ./frontend
    expose:
      - 3000
      - 3010
    ports:
      - "3000:3000"
      - "3010:3010"
    networks:
      - whip_nw
    depends_on:
      - api
    environment:
      - API_URL=http://api
    volumes:
      - ./frontend/:/app/
      - /app/node_modules/

networks:
  whip_nw:
