services:
  redis:
    profiles: ["backend"]
    image: redis
    networks:
      - whip_nw
    ports:
      - 6379:6379
  api:
    profiles: ["backend"]
    image: butter_whip/api:dev
    build:
      context: ./api
      args:
        TAG: python3.9
    ports:
      - "80:80"
    networks:
      - whip_nw
    depends_on:
      - redis
      - sched
    env_file:
      - api/app.env
    volumes:
      - ./api/app/:/app/
    command: /start-reload.sh
  sched:
    profiles: ["backend"]
    image: butter_whip/scheduler
    build: ./scheduler
    networks:
      - whip_nw
    depends_on:
      - redis
    env_file:
      - scheduler/app.env
    volumes:
      - ./scheduler/app:/entrypoint/app/
    command: "celery -A app.main worker --concurrency=1 -B -l INFO --pidfile= --logfile=/var/log/celery/%n%I.log"
  frontend:
    profiles: ["frontend"]
    image: butter_whip/frontend:dev
    build: ./frontend
    expose:
      - 3000
      - 3010
    ports:
      - "3000:3000"
      - "3010:3010"
    networks:
      - whip_nw
    depends_on:
      - api
    environment:
      - API_URL=http://api
    volumes:
      - ./frontend/:/app/
      - /app/node_modules/

networks:
  whip_nw:
