services:
  redis:
    image: redis
    networks:
      - whip_nw
  
  api:
    image: butter_whip/api
    build: ./api
    ports:
      - "80:80"
    networks:
      - whip_nw
    depends_on:
      - redis
      - sched
    env_file:
      - api/app.env
    volumes:
      - ./api/app/:/app/
    command: /start-reload.sh

  sched:
    image: butter_whip/scheduler
    build: ./scheduler
    networks:
      - whip_nw
    depends_on:
      - redis
    env_file:
      - scheduler/app.env
    volumes:
      -./scheduler/app:/app/
    command: celery -A app -l INFO --pidfile=/var/run/celery/%n.pid --logfile=/var/log/celery/%n%I.log

networks:
  whip_nw:
